In [1]:
import pandas as pd
import numpy as np

In [2]:
midwestpath='Resources/MidwestCamp.csv'
northeastpath='Resources/NortheastCamp.csv'
southpath='Resources/SouthCamp.csv'
southwestpath='Resources/SouthwestCamp.csv'

In [3]:
midwest_df=pd.read_csv(midwestpath, engine='python')
northeast_df=pd.read_csv(northeastpath, engine='python')
south_df=pd.read_csv(southpath, engine='python')
southwest_df=pd.read_csv(southwestpath, engine='python')

In [4]:
midwest_df

,Unnamed: 0,Long,Lat,Code,Campground,Type,City,State
0,NaN,-92.875,42.953,ACKL,Ackley Creek County Park,CP,Marble Rock,IA
1,NaN,-93.724,41.738,ACOR,Acorn Valley - Saylorville Lake,COE,Des Moines,IA
2,NaN,-94.643,41.498,ADAI,Adair City Park,CP,Adair,IA
3,NaN,-92.210,43.120,ADOL,Adolph Munson Park,CP,New Hampton,IA
4,NaN,-92.348,43.090,AIRP,Airport Lake Park,CP,New Hampton,IA
...,...,...,...,...,...,...,...,...
3162,NaN,-92.691,45.014,WILL,Willow River State Park,SP,Hudson,WI
3163,NaN,-88.861,45.930,WIND,Windsor Dam,NF,Eagle River,WI
3164,NaN,-90.220,43.659,WONE,Wonewoc Legion Park,CP,Wonewon,WI
3165,NaN,-91.116,42.994,WYAL,Wyalusing State Park,SP,Bagley,WI
3166,NaN,-89.971,42.769,YELL,Yellowstone Lake State Park,SP,Blanchardville,WI

In [5]:
northeast_df

,Unnamed: 0,Long,Lat,Code,Campground,Type,City,State
0,NaN,-73.098,41.651,BLAC,Black Rock State Park,SP,Thomaston,CT
1,NaN,-72.342,41.484,DEVI,Devils Hopyard State Park,SP,East Haddam,CT
2,NaN,-71.811,41.534,GREE,Green Falls - Pachaug State Forest,SF,NaN,CT
3,NaN,-72.556,41.265,HAMM,Hammonasset State Park,SP,Madison,CT
4,NaN,-73.004,41.935,HAWS,Haws Memorial - American Legion State Forest,SF,Barkhamsted,CT
...,...,...,...,...,...,...,...,...
713,NaN,-81.428,37.622,TWIN,Twin Falls Resort State Park,SP,Mullens,WV
714,NaN,-79.994,39.308,TYGA,Tygart Lake State Park,SP,Grafton,WV
715,NaN,-80.975,37.846,WARR,War Ridge - New River National Scenic River,NP,Meadow Bridge,WV
716,NaN,-80.012,38.007,WEST,West Shore - Lake Sherwood,NF,Eastern,WV
717,NaN,-78.689,38.925,WOLF,Wolf Gap,NF,Wardensville,WV

In [6]:
south_df

,Unnamed: 0,Lat,Long,Code,Campground,Type,City,State
0,NaN,-85.214,32.977,AMIT,Amity,COE,Lanett,AL
1,NaN,-85.963,33.621,ANNI,Anniston Army Depot RV Military,MIL,Anniston,AL
2,NaN,-87.924,34.427,BEA3,Bear Creek Lakes,AUTH,Russellville,AL
3,NaN,-87.966,34.448,BEA2,Bear Creek Lakes,AUTH,Hodges,AL
4,NaN,-87.422,31.806,BELL,Bells Landing,COE,Camden,AL
...,...,...,...,...,...,...,...,...
2120,NaN,-95.151,30.665,WOLP,Wolf Creek Park - Lake Livingston,AUTH,NaN,TX
2121,NaN,-100.646,36.227,WOLC,Wolf Creek Park - Perryton,CP,Perryton,TX
2122,NaN,-96.535,30.295,YEGU,Yegua Creek - Lake Somerville,COE,Somerville,TX
2123,NaN,-97.129,29.305,YOAK,Yoakum City Park,CP,Yoakum,TX
2124,NaN,-102.818,33.049,YOAK,Yoakum County Park,CP,Denver City,TX

In [7]:
southwest_df

,Unnamed: 0,Lat,Long,Code,Campground,Type,City,State
0,NaN,-110.861,32.180,AGAV,Agave Gulch Military,MIL,NaN,AZ
1,NaN,-113.579,34.231,ALAM,Alamo Lake State Park,SP,Wenden,AZ
2,NaN,-109.153,33.895,ALPI,Alpine Divide,NF,Alpine,AZ
3,NaN,-112.561,34.589,ALTO,Alto Pit,NF,Prescott,AZ
4,NaN,-110.366,31.560,APAF,Apache Flats Military - Fort Huachuca,MIL,Sierra Vista,AZ
...,...,...,...,...,...,...,...,...
1467,NaN,-111.644,41.797,WOOD,Wood Camp,NF,Logan,UT
1468,NaN,-110.637,40.536,YEP1,Yellow Pine,NF,Mountain Home,UT
1469,NaN,-111.173,40.631,YEP2,Yellow Pine,NF,Kamas,UT
1470,NaN,-110.337,40.542,YELL,Yellowstone,NF,Mountain Home,UT
1471,NaN,-110.333,40.546,YELB,Yellowstone Bridge,NF,Altonah,UT

In [8]:
campgrounds_df = midwest_df.append(northeast_df)
campgrounds_df = campgrounds_df.append(south_df)
campgrounds_df = campgrounds_df.append(southwest_df)
campgrounds_df

,Unnamed: 0,Long,Lat,Code,Campground,Type,City,State
0,NaN,-92.875,42.953,ACKL,Ackley Creek County Park,CP,Marble Rock,IA
1,NaN,-93.724,41.738,ACOR,Acorn Valley - Saylorville Lake,COE,Des Moines,IA
2,NaN,-94.643,41.498,ADAI,Adair City Park,CP,Adair,IA
3,NaN,-92.210,43.120,ADOL,Adolph Munson Park,CP,New Hampton,IA
4,NaN,-92.348,43.090,AIRP,Airport Lake Park,CP,New Hampton,IA
...,...,...,...,...,...,...,...,...
1467,NaN,41.797,-111.644,WOOD,Wood Camp,NF,Logan,UT
1468,NaN,40.536,-110.637,YEP1,Yellow Pine,NF,Mountain Home,UT
1469,NaN,40.631,-111.173,YEP2,Yellow Pine,NF,Kamas,UT
1470,NaN,40.542,-110.337,YELL,Yellowstone,NF,Mountain Home,UT
1471,NaN,40.546,-110.333,YELB,Yellowstone Bridge,NF,Altonah,UT

In [9]:
campgrounds_df.dropna()

campgrounds_df = campgrounds_df[['Long', 
                            'Lat', 
                            'Code', 
                            'Campground', 
                            'Type', 
                            'City', 
                            'State']]
campgrounds_df

,Long,Lat,Code,Campground,Type,City,State
0,-92.875,42.953,ACKL,Ackley Creek County Park,CP,Marble Rock,IA
1,-93.724,41.738,ACOR,Acorn Valley - Saylorville Lake,COE,Des Moines,IA
2,-94.643,41.498,ADAI,Adair City Park,CP,Adair,IA
3,-92.210,43.120,ADOL,Adolph Munson Park,CP,New Hampton,IA
4,-92.348,43.090,AIRP,Airport Lake Park,CP,New Hampton,IA
...,...,...,...,...,...,...,...
1467,41.797,-111.644,WOOD,Wood Camp,NF,Logan,UT
1468,40.536,-110.637,YEP1,Yellow Pine,NF,Mountain Home,UT
1469,40.631,-111.173,YEP2,Yellow Pine,NF,Kamas,UT
1470,40.542,-110.337,YELL,Yellowstone,NF,Mountain Home,UT
1471,40.546,-110.333,YELB,Yellowstone Bridge,NF,Altonah,UT

In [13]:
campgrounds = campgrounds_df.sort_values('State')
campgrounds.head()

      Long     Lat  Code                    Campground Type         City State
99  31.903 -86.678  SHER       Sherling Lake City Park   CP  Greenville.    AL
14  34.472 -86.051  BUCK       Bucks Pocket State Park   SP    Grove Oak    AL
15  33.450 -87.349  BURC        Burchfield Branch Park  COE        Adger    AL
16  32.957 -85.218  BURN                 Burnt Village   CP       Lanett    AL
17  34.572 -86.230  CATH  Cathedral Caverns State Park   SP    Woodville    AL