In [1]:
import pandas as pd
import numpy as np

In [2]:
midwestpath='Resources/MidwestCamp.csv'
northeastpath='Resources/NortheastCamp.csv'
southpath='Resources/SouthCamp.csv'
southwestpath='Resources/SouthwestCamp.csv'
westpath='Resources/WestCamp.csv'

In [3]:
midwest_df=pd.read_csv(midwestpath, engine='python')
northeast_df=pd.read_csv(northeastpath, engine='python')
south_df=pd.read_csv(southpath, engine='python')
southwest_df=pd.read_csv(southwestpath, engine='python')
west_df=pd.read_csv(westpath, engine='python')

In [4]:
midwest_df

,Unnamed: 0,Long,Lat,Code,Campground,Type,City,State
0,NaN,42.953,-92.875,ACKL,Ackley Creek County Park,CP,Marble Rock,IA
1,NaN,41.738,-93.724,ACOR,Acorn Valley - Saylorville Lake,COE,Des Moines,IA
2,NaN,41.498,-94.643,ADAI,Adair City Park,CP,Adair,IA
3,NaN,43.120,-92.210,ADOL,Adolph Munson Park,CP,New Hampton,IA
4,NaN,43.090,-92.348,AIRP,Airport Lake Park,CP,New Hampton,IA
...,...,...,...,...,...,...,...,...
3162,NaN,45.014,-92.691,WILL,Willow River State Park,SP,Hudson,WI
3163,NaN,45.930,-88.861,WIND,Windsor Dam,NF,Eagle River,WI
3164,NaN,43.659,-90.220,WONE,Wonewoc Legion Park,CP,Wonewon,WI
3165,NaN,42.994,-91.116,WYAL,Wyalusing State Park,SP,Bagley,WI
3166,NaN,42.769,-89.971,YELL,Yellowstone Lake State Park,SP,Blanchardville,WI

In [5]:
northeast_df

,Unnamed: 0,Long,Lat,Code,Campground,Type,City,State
0,NaN,41.651,-73.098,BLAC,Black Rock State Park,SP,Thomaston,CT
1,NaN,41.484,-72.342,DEVI,Devils Hopyard State Park,SP,East Haddam,CT
2,NaN,41.534,-71.811,GREE,Green Falls - Pachaug State Forest,SF,NaN,CT
3,NaN,41.265,-72.556,HAMM,Hammonasset State Park,SP,Madison,CT
4,NaN,41.935,-73.004,HAWS,Haws Memorial - American Legion State Forest,SF,Barkhamsted,CT
...,...,...,...,...,...,...,...,...
713,NaN,37.622,-81.428,TWIN,Twin Falls Resort State Park,SP,Mullens,WV
714,NaN,39.308,-79.994,TYGA,Tygart Lake State Park,SP,Grafton,WV
715,NaN,37.846,-80.975,WARR,War Ridge - New River National Scenic River,NP,Meadow Bridge,WV
716,NaN,38.007,-80.012,WEST,West Shore - Lake Sherwood,NF,Eastern,WV
717,NaN,38.925,-78.689,WOLF,Wolf Gap,NF,Wardensville,WV

In [6]:
south_df

,Unnamed: 0,Long,Lat,Code,Campground,Type,City,State
0,NaN,32.977,-85.214,AMIT,Amity,COE,Lanett,AL
1,NaN,33.621,-85.963,ANNI,Anniston Army Depot RV Military,MIL,Anniston,AL
2,NaN,34.427,-87.924,BEA3,Bear Creek Lakes,AUTH,Russellville,AL
3,NaN,34.448,-87.966,BEA2,Bear Creek Lakes,AUTH,Hodges,AL
4,NaN,31.806,-87.422,BELL,Bells Landing,COE,Camden,AL
...,...,...,...,...,...,...,...,...
2120,NaN,30.665,-95.151,WOLP,Wolf Creek Park - Lake Livingston,AUTH,NaN,TX
2121,NaN,36.227,-100.646,WOLC,Wolf Creek Park - Perryton,CP,Perryton,TX
2122,NaN,30.295,-96.535,YEGU,Yegua Creek - Lake Somerville,COE,Somerville,TX
2123,NaN,29.305,-97.129,YOAK,Yoakum City Park,CP,Yoakum,TX
2124,NaN,33.049,-102.818,YOAK,Yoakum County Park,CP,Denver City,TX

In [7]:
southwest_df

,Unnamed: 0,Long,Lat,Code,Campground,Type,City,State
0,NaN,32.180,-110.861,AGAV,Agave Gulch Military,MIL,NaN,AZ
1,NaN,34.231,-113.579,ALAM,Alamo Lake State Park,SP,Wenden,AZ
2,NaN,33.895,-109.153,ALPI,Alpine Divide,NF,Alpine,AZ
3,NaN,34.589,-112.561,ALTO,Alto Pit,NF,Prescott,AZ
4,NaN,31.560,-110.366,APAF,Apache Flats Military - Fort Huachuca,MIL,Sierra Vista,AZ
...,...,...,...,...,...,...,...,...
1467,NaN,41.797,-111.644,WOOD,Wood Camp,NF,Logan,UT
1468,NaN,40.536,-110.637,YEP1,Yellow Pine,NF,Mountain Home,UT
1469,NaN,40.631,-111.173,YEP2,Yellow Pine,NF,Kamas,UT
1470,NaN,40.542,-110.337,YELL,Yellowstone,NF,Mountain Home,UT
1471,NaN,40.546,-110.333,YELB,Yellowstone Bridge,NF,Altonah,UT

In [8]:
west_df

,Unnamed: 0,Long,Lat,Code,Campground,Type,City,State
0,NaN,61.086,-146.343,ALLI,Allison Point,CP,Valdez,AK
1,NaN,59.768,-151.865,ANCH,Anchor River State Rec Area,SRA,Anchor Point,AK
2,NaN,66.566,-150.810,ARCT,Arctic Circle - Dalton Hwy,BLM,NaN,AK
3,NaN,58.381,-134.737,AUKV,Auk Village,NF,Juneau,AK
4,NaN,60.751,-149.256,BERT,Bertha Creek,NF,Hope,AK
...,...,...,...,...,...,...,...,...
3921,NaN,43.196,-110.885,WOLF,Wolf Creek,NF,Jackson,WY
3922,NaN,43.932,-109.132,WOOD,Wood River,NF,NaN,WY
3923,NaN,41.504,-111.020,WOOD,Woodruff Narrows/Bear River Access - WGF,SFW,Evanston,WY
3924,NaN,42.699,-108.930,WORT,Worthen Meadows,NF,Lander,WY
3925,NaN,41.255,-105.411,YELL,Yellow Pine,NF,Laramie,WY

In [9]:
campgrounds_df = midwest_df.append(northeast_df)
campgrounds_df = campgrounds_df.append(south_df)
campgrounds_df = campgrounds_df.append(southwest_df)
campgrounds_df = campgrounds_df.append(west_df)
campgrounds_df

,Unnamed: 0,Long,Lat,Code,Campground,Type,City,State
0,NaN,42.953,-92.875,ACKL,Ackley Creek County Park,CP,Marble Rock,IA
1,NaN,41.738,-93.724,ACOR,Acorn Valley - Saylorville Lake,COE,Des Moines,IA
2,NaN,41.498,-94.643,ADAI,Adair City Park,CP,Adair,IA
3,NaN,43.120,-92.210,ADOL,Adolph Munson Park,CP,New Hampton,IA
4,NaN,43.090,-92.348,AIRP,Airport Lake Park,CP,New Hampton,IA
...,...,...,...,...,...,...,...,...
3921,NaN,43.196,-110.885,WOLF,Wolf Creek,NF,Jackson,WY
3922,NaN,43.932,-109.132,WOOD,Wood River,NF,NaN,WY
3923,NaN,41.504,-111.020,WOOD,Woodruff Narrows/Bear River Access - WGF,SFW,Evanston,WY
3924,NaN,42.699,-108.930,WORT,Worthen Meadows,NF,Lander,WY
3925,NaN,41.255,-105.411,YELL,Yellow Pine,NF,Laramie,WY

In [10]:
campgrounds_df.dropna()

campgrounds_df = campgrounds_df[['Lat', 
                            'Long', 
                            'Code', 
                            'Campground', 
                            'Type', 
                            'City', 
                            'State']]
campgrounds_df

,Long,Lat,Code,Campground,Type,City,State
0,42.953,-92.875,ACKL,Ackley Creek County Park,CP,Marble Rock,IA
1,41.738,-93.724,ACOR,Acorn Valley - Saylorville Lake,COE,Des Moines,IA
2,41.498,-94.643,ADAI,Adair City Park,CP,Adair,IA
3,43.120,-92.210,ADOL,Adolph Munson Park,CP,New Hampton,IA
4,43.090,-92.348,AIRP,Airport Lake Park,CP,New Hampton,IA
...,...,...,...,...,...,...,...
3921,43.196,-110.885,WOLF,Wolf Creek,NF,Jackson,WY
3922,43.932,-109.132,WOOD,Wood River,NF,NaN,WY
3923,41.504,-111.020,WOOD,Woodruff Narrows/Bear River Access - WGF,SFW,Evanston,WY
3924,42.699,-108.930,WORT,Worthen Meadows,NF,Lander,WY
3925,41.255,-105.411,YELL,Yellow Pine,NF,Laramie,WY

In [11]:
campgrounds = campgrounds_df.sort_values('State')
campgrounds.head()

      Long      Lat  Code                Campground Type        City State
91  60.416 -149.381  TRAI               Trail River   NF  Moose Pass    AK
67  62.868 -145.535  PAXS               Paxson Lake  BLM      Gakona    AK
66  65.370 -147.088  OPHI  Ophir Creek - Steese Hwy  BLM         NaN    AK
65  56.580 -132.741  OHME               Ohmer Creek   NF  Petersburg    AK
64  60.051 -151.668  NINI  Ninilchik State Rec Area  SRA   Ninilchik    AK

In [12]:
campgrounds.to_csv('campgrounds.csv')